### ISSUE TITLE
Dependencies + project setup

### ISSUE THREAD

**Issue by zaklaus** [reguider/librg#1]
We are currently working at replacing our former dependencies.

The project structure will be slightly changed.

- [x] bitstream container (replaces @DavoSK's C++ bitstream class utility)
- [x] math library
- [x] Spatial distance tree culling (replaces our former solution)
- [x] entity system (replaces entityx)
- [x] new project structure

**Comment by Inlife** [comment]
done

**Comment by Inlife** [comment]
![artboard](https://user-images.githubusercontent.com/2182108/29322933-0be3cb06-81e8-11e7-9cef-aa6be82c9faa.png)

**Comment by Inlife** [comment]
![artboard](https://user-images.githubusercontent.com/2182108/33219640-19238a96-d14c-11e7-81d0-79cd61f6f2d1.png)

**Comment by inlife** [comment]
![dark_bg](https://user-images.githubusercontent.com/2182108/33563061-a29a41d6-d91f-11e7-8003-d11298485bd9.png)
![white_transp](https://user-images.githubusercontent.com/2182108/33563062-a2bcc9ae-d91f-11e7-8637-fe96a8454eed.png)
![wireframe](https://user-images.githubusercontent.com/2182108/33563064-a2da8a66-d91f-11e7-9cf9-a105f95782c1.png)



![no_bg](https://user-images.githubusercontent.com/2182108/33563067-a3810e72-d91f-11e7-9a30-b492b4600d66.png)

![round_white](https://user-images.githubusercontent.com/2182108/33563068-a3c4336e-d91f-11e7-845f-258343ceebba.png)

**Comment by inlife** [comment]
[png+svg.zip](https://github.com/librg/librg/files/1527872/png.svg.zip)

**Comment by zaklaus** [comment]
![openmf_capitalized_copy](https://user-images.githubusercontent.com/9026786/43263060-7c0a8b86-90e2-11e8-96e3-3e71e559f62a.png)

**Comment by inlife** [comment]
![librg_splash](https://user-images.githubusercontent.com/2182108/46903598-f6e48380-cedf-11e8-8b05-c89e80f60b73.png)

**Comment by yewpad** [comment]
Can somebody please tell me what the name of the font is that is being used?

**Comment by inlife** [comment]
sure, its `Avenir Next`

**Comment by inlife** [comment]
![librg_world_replication](https://user-images.githubusercontent.com/2182108/83945607-87d64400-a814-11ea-8897-3c268b26b0f7.png)

**Comment by zaklaus** [comment]
![81554853-31e6bb80-9390-11ea-94c7-c25ab15e57eb](https://user-images.githubusercontent.com/9026786/103413377-8afe9c00-4b79-11eb-9cda-1caa4800b487.png)

**Comment by zaklaus** [comment]
![Screenshot 2021-02-19 171655](https://user-images.githubusercontent.com/9026786/108531043-8bdcc000-72d6-11eb-9a33-4092411a57bd.png)

**Comment by inlife** [comment]
![map_with_librg](https://user-images.githubusercontent.com/2182108/189517563-ae2e396d-6d36-48aa-b07a-597413a8d3ec.png)
![map_no_librg](https://user-images.githubusercontent.com/2182108/189517567-31ef8f5a-526a-4442-b656-453318c58089.png)
